version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - /var/lib/cassandra
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - /var/lib/grafana
    networks:
      - backend
    depends_on:
      - cassandra

networks:
  backend: